volumes:
  pg_data:


networks:
  network:
    driver: bridge
    external: false

services:
  django-app:
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DEBUG: 0
    networks:
      - network
